### ISSUE TITLE
Add access to OpenShift for Digital Marketplace namespace

### ISSUE THREAD

**Issue by mark-a-wilson** [BCDevOps/devops-requests#1086]
_Hi folks,
I'm submitting this request on behalf of incoming product owner for Digital Marketplace, Steve Chapman (@SteveChapmanBCDX / @scchapma). Previous product owner is Zach Woodward. We don't know what the OCP4 namespace is, but it's the one for the Digital Marketplace application (https://github.com/bcgov/digital_marketplace).
~Mark_

---

## Step 0
**Are you the product owner or technical lead?**
Incoming product owner, Steve Chapman (@SteveChapmanBCDX / @scchapma), can verify this request.

**Do you have a GitHub account?**
Yes

**Do you have 2-factor-authentication enabled with your GitHub account?**
Yes

## Step 1
Are you requesting to:
- [x] grant user access
- [ ] remove user access

## Step 2
Fill out the following fields

**Parul Dubedy**
* Full Name: Parul Mishra Dubedy
* GitHub ID: @parulmishra 
* Business Email Address: Parul.Dubedy@gov.bc.ca
* Organization: Strategic Design & Delivery Branch, CITZ
* Project Role: Developer

**Jonathan Sharman**
* Full Name: Jonathan Sharman
* GitHub ID: @thegentlemanphysicist  
* Business Email Address: Jonathan.Sharman@gov.bc.ca
* Organization: Strategic Design & Delivery Branch, CITZ
* Project Role: Developer

**Comment by SteveChapmanBCDX** [comment]
Hi @caggles -

Please also grant me admin credentials (modification of Step 2).

**Steve Chapman**

Full Name: Steve Chapman
GitHub ID: @SteveChapmanBCDX 
Business Email Address: Steve.Chapman@gov.bc.ca
Organization: Strategic Design & Delivery Branch, CITZ
Project Role: Product Owner

**Comment by SteveChapmanBCDX** [comment]
Hi @caggles -

Andrew Sutherland added me as an admin to the Digital Marketplace OCP4 namespace today, but I still cannot access that namespace.

Can your team take a look here?  The Exchange Lab team is blocked from completing an urgent issue right now, and we need access to this namespace.

Regards,
Steve

**Comment by caggles** [comment]
Hi @SteveChapmanBCDX ! There is nothing further that should be blocking your access to the namespace - you've already been added to the org and should therefore have access to the console, and if you were added as an admin to the namespace, that should be all that's necessary. Can you provide more details on what exactly happens when you try to access the namespace? Any error messages or anything?

**Comment by caggles** [comment]
Oh, and if you could provide the namespace name (in the form abcdef-tools, -dev, -test or -prod), that would help me to troubleshoot the issue further!

**Comment by SteveChapmanBCDX** [comment]
Hi @caggles!   Thanks for responding so quickly.

This is what I'm seeing on my console:
<img width="1369" alt="Screen Shot 2021-05-05 at 12 58 08 PM" src="https://user-images.githubusercontent.com/36771389/117204419-206aa080-ada5-11eb-8ddc-e0d7efb67225.png">

I've refreshed the browser several times and cleared the cache.  I've tried to sign out, but I wasn't able to do that.

I'm waiting on the namespace name - I'l forward that to you when I receive it.

**Comment by SteveChapmanBCDX** [comment]
@caggles - Here's the namespace => **ccc866-dev/test/prod**

**Comment by SteveChapmanBCDX** [comment]
@caggles  - I still don't have access to these namespaces - I think there may be a problem with my OCP4 account.  I'll contact you on Teams.

**Comment by caggles** [comment]
Hi @SteveChapmanBCDX - Sorry, I didn't catch this message yesterday, that's my bad! I found the issue! Usernames in OCP4 have the format `<name>@github` so yours would be `SteveChapmanBCDX@github`. But whoever added you to the namespace only added the appropriate permissions to a (non-existent) user called just `SteveChapmanBCDX` and that's why it didn't work! Please pass this info along so they know for next time :)

**Comment by SteveChapmanBCDX** [comment]
@caggles - Thank you!
