### ISSUE TITLE
OpenShift Access for Developer

### ISSUE THREAD

**Issue by Travis-A-Clark** [BCDevOps/devops-requests#1246]
I am a PO requesting OpenShift access for a new developer on my team. See info below. Thanks!

Full Name: Dennis Cinco
GitHub ID: telusdcinco
Business Email Address: Dennis.Cinco@telus.com
Organization: Telus
Project Role: Developer
OpenShift Projects/Namespaces: Performance
332842-dev
332842-prod
332842-test
332842-tools

**Comment by patricksimonian** [comment]
@Travis-A-Clark we do not grant access to namespaces for developers. Your technical lead or admin will be able to do that. Just make sure to add them as `telusdcinco@github` when you do create rolebindings. That being said  @telusdcinco will need to be apart of the bcdevops github organization in order to gain access to OCP itself. 

You can do this by inviting him to the orgs with [just ask](https://just-ask-web-bdec76-prod.apps.silver.devops.gov.bc.ca/)

**Comment by patricksimonian** [comment]
@Travis-A-Clark I've noticed you invited @telusdcinco . I will close this issue :)
