### ISSUE TITLE
New Request Type: Migrate repo from bcgov-c to other Organization

### ISSUE THREAD

**Issue by NicoledeGreef** [BCDevOps/devops-requests#1557]
## Step 2
Please answer the following questions about the new request type:

1. **What is it?** Move repo from bcgov-c to bcgov organization
2. **Why should this be a new request type?** It seems I do not have permissions to do this.  In the repo within bcgov-c I cannot see Settings for the repo.
3. **What information is required to fulfill this request?** Origin org/repo & Destination org/repo
4. **What is the end result?** The repo should appear within the destination repo (bcgov, for example).
5.

**Comment by MonicaG** [comment]
Hi @NicoledeGreef I followed up with @IanKWatts who administers ArgoCD. Unfortunately, we cannot move the [tenant-gitops-ea352d repo](https://github.com/bcgov-c/tenant-gitops-ea352d) to the bcgov org. The reason is because of the automation associated with Argo CD. If you would like other users to be able to see the contents of the repo, you could add those users to the 'readers' list in 'gitOpsMembers' of your GitOpsTeam, although those people must be members of the bcgov-c org.

If I have misunderstood your request, please let me know.

**Comment by NicoledeGreef** [comment]
> Hi @NicoledeGreef I followed up with @IanKWatts who administers ArgoCD. Unfortunately, we cannot move the [tenant-gitops-ea352d repo](https://github.com/bcgov-c/tenant-gitops-ea352d) to the bcgov org. The reason is because of the automation associated with Argo CD. If you would like other users to be able to see the contents of the repo, you could add those users to the 'readers' list in 'gitOpsMembers' of your GitOpsTeam, although those people must be members of the bcgov-c org.
> 
> If I have misunderstood your request, please let me know.

Thank you for the follow-up and investigation, @MonicaG. It sounds like there is an Argo CD dependency on using bcgov-c?

It was our understanding that our repos should not stay in **bcgov-c** for more than 11 months and we thought we needed to move it to another Organization.  We were targeting **bcgov** as there was nothing in tenant-gitops-ea352d that was unable to move there. We will soon have a private Organization in GitHub as well if that is desirable.

**Comment by MonicaG** [comment]
Hi @NicoledeGreef,

Yes, the tenant-gitops-XXXX repos need to stay in bcgov-c because of the argocd dependencies. Non gitops repos that are in bcgov-c should move to bcgov within a year.

You mention having a private Organization is GitHub soon. What organization is that? What will it be used for?

Thanks!

**Comment by NicoledeGreef** [comment]
Ah - thank you for the clarification that not all repos need to move out of bcgov-c.

I anticipate requesting **bcgov-finance** along with several GitHub Enterprise licenses. The new private Org will host repos that pertain to sensitive matters.
