### ISSUE TITLE
Request Membership

### ISSUE THREAD

**Issue by KennethPorter1** [BCDevOps/devops-requests#207]
## Step 0

**Are you a member of the BCGOV GitHub Organization already?**
Please note that **new users may not request access for themselves**. If you are not a member already, please talk to whoever that performed the onboarding/introduction of the BCGov DevOps Platform and BCDevExchange, and ask that contact to create this request for you.

**Do you actually need the team member to be a member of the organization?**
- Often, it works just fine to have a team member as a Collaborator on your repository, without them being a member of the `bcgov` GitHub organization. Before submitting this request, consider whether you could simply invite your team member to contribute as a Collaborator.  
  Instructions [here](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/inviting-collaborators-to-a-personal-repository).

**Are you the admin of your project's BCGOV GitHub Repository?**
If not, you need to ask your project repo's admin to make this request.

## Step 1
Visit DevHub for detailed instruction on creating a request:
https://developer.gov.bc.ca/Getting-Started-on-the-DevOps-Platform/How-to-request-new-GitHub-user-access-or-repository-creation

## Step 2
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

## Step 4
Are you requesting to:
- [x] Invite a user
- [ ] Remove a user

## Step 5
Fill out the following fields

* Project Name: Community Energy and Emissions Inventory (CEEI) Database Review and Technical Recommendations
* GitHub Org: private
* Full Name: Ken Porter
* GitHub ID: @KennethPorter1 
* GitHub Account 2FA Confirmed: ?
* Email address: Kenneth.Porter@gov.bc.ca
* Organization: Climate Action Secretariat
* Project Role: Product Owner
* GitHub Team to Join (if exists): BC Government GitHub organization (https://github.com/bcgov)
* Existing GitHub Repo: https://github.com/KennethPorter1/CEEI/

**Note** that the platform services team will be removing GitHub Org access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by ShellyXueHan** [comment]
@KennethPorter1 Hi Kenneth, we do not grant access to users via self-request. Please provide more information on your request. Is your team on the OpenShift platform? Do you need to create/migrate a repository in the bcgov-c (private) GitHub organization? Private repository is meant to be temporary, not sensitive information should be in the repo. What's the reasoning for being closed source? Lastly, please provide a contact from the exchange lab/OpenShift platform that could submit the access request for you. Thank you!

**Comment by mark-a-wilson** [comment]
Hi @ShellyXueHan & @KennethPorter1 ...

Shelly, I was the one who advised Ken put in this request, but I now think it's not necessary and can be closed/disregarded. 

Ken just needs a repository in order to run [this Code With Us opportunity](https://www.bcdevexchange.org/opportunities/cwu/opp-community-energy-and-emissions-inventory--ceei--database-review-and-technical-recommendations).  However, the product that's being procured through the opportunity is not code, but rather reports and plans. 

I originally thought the appropriate place for this would be under **github.com/bcgov**, but now that I understand better the intention to keep **github.com/bcgov** more manicured for active, maintained **_code_** projects, and ones that are largely using the Platform, I think it will be fine for Ken to just use [this repository under his own GitHub account](https://github.com/KennethPorter1/CEEI/) to answer questions about the opportunity and have documents delivered in the open. 

cc @ZachWoodward - Please advise if you think this is inappropriate and should indeed live under **github.com/bcgov**?

**Comment by ZachWoodward** [comment]
This makes sense to me.

Regards,
Zachary Woodward

**Comment by caggles** [comment]
Okay then, I'm going to close this as "not necessary" :)
