### ISSUE TITLE
add request type: Human Help Needed

### ISSUE THREAD

**Issue by wenzowski** [BCDevOps/devops-requests#223]
Sometimes teams have #devops-requests that are super trivial but don't fit one of the types in the list. This issues flow has now been configured so that issues that are not typed according to one of the eight templated options look like they cannot be submitted.

The link to "Human Help Needed" is nice, but as a link prevents opening tickets for catchall issues that don't quite fit the templated flows.

Can we swap the Human Help Needed with a new catchall issue template? That way we can record what human help is needed in the issues list.

<img width="934" alt="Screen Shot 2020-03-09 at 9 52 59 AM" src="https://user-images.githubusercontent.com/597920/76237717-f262ee00-61eb-11ea-95a1-1d0a41de3134.png">

**Comment by wenzowski** [comment]
possible dupe #39 though to solve that with this perhaps points at asking people to declare which team's human help is needed?

**Comment by caggles** [comment]
hey @wenzowski - the intent here is to avoid having teams open untyped tickets. If you have an issue that doesn't fall within the bounds of a normal ticket, we would prefer that you ask about it on RC instead of opening a ticket for it. @ShellyXueHan and I only have the manpower to do those requests that are specifically within our scope and the idea with disallowing untyped tickets is to discourage people from using it to make requests that aren't within our scope. We aren't a tech support team - we don't have the manpower for that!

That being said, if you think that we're missing a specific request type (even if that request type doesn't come up super often), please do let us know and we'll add that specific request type to the list :)

**Comment by wenzowski** [comment]
@caggles this is of course your call, and I totally understand the need to consider [bounded rationality](https://plato.stanford.edu/entries/bounded-rationality/): in addition to the time/staffing concerns you mention, the tractability of the issues being surfaced is limited by only addressing a whitelist of issue types instead of the complexity of the world.

However, the Rocket.Chat-only approach falls short, especially now that the #devops-requests channel is gone. I'd really like somewhere for these kind of things to be tracked even if not this repo. Things get lost/ignored/buried in Rocket Chat, and that's not a criticism of the community but the fundamental nature of chat.

Fundamentally, there's a mismatch here:

> Human help needed
> Please come talk to BCGov Developer Experience if you have questions/issues.
> `[Open](https://developer.gov.bc.ca/)`

This repo appears to be configured as if you accept that human help is sometimes needed even though it's not immediately in your scope, and that it needs to be somehow actioned nonetheless. However the expectation of that call to action I have as a user is that by clicking "Open" we will be guided toward a method to access _Human Help_ and instead we get a page with some help topics and no contact method or issue triage methodology. As a result, I'm asking for some way to track items of unknown type so they can be publicly triaged (even in a self-service way) rather than slingshotting anything untyped around your request process and escalating immediately to a hard interrupt of your workday.

cc @Maralsotoudehnia

**Comment by caggles** [comment]
Ideally, we'll end up filling out our whitelist of requests so that just about _every_ valid request is covered. There are a limited number of things that Shelly and I are capable of doing that the rest of the developers in the community are not, so we would aim to have all of those things covered in our templates. Anything outside of those requests are going to require a fuller conversation with us anyway, so it would probably be better to begin that process with a meeting invite rather than an issue. 

However, I do think your point regarding the "Human Help" link is valid - that should link to a specific item of documentation with a fuller explanation of how to get the human help required. Linking just to the regular homepage for DevHub isn't sufficient or particularly helpful, for sure. I'll start working on some docs to cover that.

But in the meantime, I noticed that you linked a Sonarqube permissions ticket above - a ticket type having to do with requesting github apps makes a lot of sense, to me. Would this specific problem be helped if we added one of those?

**Comment by wenzowski** [comment]
> a ticket type having to do with requesting github apps
much appreciated :)

and if "human help"
> should link to a specific item of documentation with a fuller explanation of how to get the human help required
then, perfect!

sounds like a great way to close this one out if that works for you

**Comment by caggles** [comment]
Perfect, thank you for the feedback! We're in the process of getting all that set up, but I'll close this ticket in the meantime :)
