### ISSUE TITLE
GitHub Org Membership Request

### ISSUE THREAD

**Issue by ActionAnalytics** [BCDevOps/devops-requests#289]
## Step 1
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues
Confirmed

## Step 2
Please answer the following questions about the new request type:

1. **What is it?** Please provide an overview of what the request should do.
I have asked for access to bcdevops for the ability to create new repos following the same pattern as bcgov and I've been directed here.    

2. **Why should this be a new request type?** A good rule of thumb: Is this task straightforward (or something that could be automated)? Does it involve something you don't have the permissions to do? If the answer to both questions is yes, you're probably good to go ahead!
Cannot self grant the permissions.  

3. **What information is required to fulfill this request?** Do you best here - the Platform Services team can help if you're not sure!
Permission from an existing admin.  In this case this is for cloud platform work for and approved by @kelpisland who has asked that I create a new repo for the work we are undertaking (proof already provided to the team member who requested I request a new request type).  This work falls under bcdevops as it is cluster cloud work, following the pattern in use by https://github.com/BCDevOps/OpenShift4-RollOut but in this case specifically called out to be put in new repos under bcdevops.

4. **What is the end result?** Please provide plenty of details about what the end result should look like.
Smooth onboarding of authorized bcgov employees for enabling approved work in bcdevops.

**Comment by caggles** [comment]
This request will not be approved for the following reasons:

1. Github's permissions settings do not permit the piecemeal granting of the requested access and it is not appropriate to provide the wider access necessary in order to fulfill the request as asked.
2. Use of BCDevOps for anything but Openshift access is an exception rather than the rule, and all teams with a claim to that exception have at least one member with the required access already.

However, as there may be the occasional situation in which a user has a reason to request a new repo be made for them, I have created a new request type in which anyone without ready access to someone on their team with the requisite permissions may make a request for a new repo as required. If you still need a new repo, please feel free to request one on that issue type :)
