### ISSUE TITLE
Please Add user Ayo Ojo (Git Hub Name vesselofgold)

### ISSUE THREAD

**Issue by jennifer-dowd** [BCDevOps/devops-requests#411]
## Step 0

**Are you the Technical Lead?**
If not, you need to ask your team's Technical Lead role to make this request. This role should be a member of the BCGOV Github org as part of the team onboarding process.

If you do not have access to a Technical Lead to ask for membership on your behalf, or the Technical Lead has not yet obtained the membership, a member of the Platform Experience team will contact you about your request once you have submitted it.
We will need to discuss your needs in a quick meeting before this request can be processed! **Please indicate in this ticket if you need to schedule this meeting.** 
If you've already had a meeting as part of a request for an Openshift Project, please indicate that in the ticket as well.

**Do you actually need the team member to be a member of the organization?**
- Often, it works just fine to have a team member as a Collaborator on your repository, without them being a member of the `bcgov` GitHub organization. Before submitting this request, consider whether you could simply invite your team member to contribute as a Collaborator.  
  Instructions [here](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/inviting-collaborators-to-a-personal-repository).

## Step 1
Visit DevHub for detailed instruction on creating a request:
https://developer.gov.bc.ca/Getting-Started-on-the-DevOps-Platform/How-to-request-new-GitHub-user-access-or-repository-creation

## Step 2
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

## Step 4
Are you requesting to:
- [x] Invite a user
- [ ] Remove a user

## Step 5
Fill out the following fields

* Project Name: Access to the BCGov GitHub organizations
* GitHub Org: bcgov, bcgov-c
* Full Name: Ayo Ojo
* GitHub ID: @vesselofgold
* GitHub Account 2FA Confirmed: yes 
* Email address: Ayo.Ojo@gov.bc.ca
* Organization: PSSG – RoadSafety Initiative
* Project Role: Business Analyst/Technical Support
* GitHub Team to Join (if exists): bcgov-c/rsi-justice-hub
* Existing GitHub Repo: bcgov-c/jh-etk

**Note** that the platform services team will be removing GitHub Org access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by vesselofgold** [comment]
Please I think my account was removed from the bcgov-c organization by mistake. Kindly restore as it is impacting my ability to complete some of my tasks.




Thanks
Ayo
    On Wednesday, June 24, 2020, 04:30:35 PM PDT, requestron[bot] <notifications@github.com> wrote:  
 
 


This issue has now been closed. It has been completed, unless a comment indicates otherwise.

The invitation should appear in the relevant user's inbox very soon. Please ensure that they're checking the correct inbox. The invitation will show up in the inbox of whatever email address is listed as their primary address in their github profile. Please note that this request ONLY provides access to the bcgov and/or bcgov-c organizations. It does not provide access to Openshift. If you require that, please open another issue here

If you have additional problems or questions, please feel free to ask the community on RocketChat on the #devops-howto channel!

**Comment by vesselofgold** [comment]
@ShellyXueHan I guess my account (@vesselofgold) was accidentally deleted from the bcgov-c organization, Kindly help expedite action in restoring my access
