### ISSUE TITLE
Enable BCeID authentication for proof-of-concept work in Dev and Test for justicehub realm

### ISSUE THREAD

**Issue by agahchen** [BCDevOps/devops-requests#908]
## Step 0
**Are you the product owner or project admin/team lead?**

David Agahchen is the technical lead and a project admin for the existing realm (justicehub) in Dev and Test instances.
Jennifer Dowd the product owner has requested to enable BCeID-based authentication for proof-of-concept work.

**Does the Admin User have an IDIR account?**
We use IDIR authentication for Realm Admin Users, so make sure there's a *valid IDIR* for the assigned realm admin.  

**Are you requesting for Identity Provider Update?**
If so, you need to be the realm admin. Then proceed to Step 3.

Yes.

## Step 0

Skipped.

## Step 1

Skipped.

## Step 2

Skipped.

## Step 3
Field the following information.

* Project Name: RoadSafetyBC Hub

* OpenShift Project Set/s Info
  - Project set name:  5115cc-dev, 5115cc-test
  - Namespace ID: 5115cc

* For existing Keycloak realm update only
  - Realm ID: justicehub
  - Identity Provider to Add
    - [x] BCeID
    - [ ] GitHub
    - [ ] BCSC

## Step 4
Submit this ticket and email us the contact information.

For security purpose, please provide the following contact information to the email address - pathfinder@gov.bc.ca

* Email to reach out for On-Boarding meeting invitation:
* link to the GitHub ticket you just created: 
* Admin user's IDIR account: 
* Admin user's Business Email Address: 

Please note that we will only start processing your request when the email has been received.

## Step 5
After we have completed processing your request, you can proceed to creating a realm at [Realm-O-Matic](https://realm-o-matic.developer.gov.bc.ca)

**Comment by nvunnamm** [comment]
Requested approval from IDIM team. Will work on it as soon as we get Approval :)

**Comment by nvunnamm** [comment]
@agahchen As IDIM consultant, doesn’t have a Realm-o-Matic KeyCloak Realm request for the ( NameSpace 5115cc ) ‘justicehub’ online service, please can you fill out and submit the attached BCeID Self-Assessment to IDIM.Consulting@gov.bc.ca … [ https://citz.sp.gov.bc.ca/sites/SBC/IDIM/FG/Shared%20Documents/! Step 1 - fill in and submit this eService self assessment.docx ] //or// if this opportunity is the same as the ‘Road Safety Business Intelligence’ – [ eTicketting Dashboard ] opportunity, please update the 2019 RSI document and re-submit to IDIM.Consulting@gov.bc.ca So that they can approve the request and we can proceed once approved.

And also IDIM noticed that the existing justicehub realm (non-prod) appears to be integrated with Microsoft for the Saanich Police Department... Is there an intention to keep this option in place as part of the BCeID PoC body of work?

**Comment by agahchen** [comment]
@nvunnamm this is not the same realm as 'Road Safety Business Intelligence'.  This is for the 'Road Safety BC Hub' solution, aka 'justicehub'.  This is not a permanent solution, as the changes are strictly to support the proof-of-concept work.  You're correct we need to maintain the configured external identity provider.. as it is part of the PoC.  We will also be adding Verifiable Credentials-based authentication.  Would you be able to send me the self assessment doc?  I can ping you via Rocket.Chat DM to follow up.

**Comment by jennifer-dowd** [comment]
FYI - connected with IDIM Consulting via email. I have submitted the required form they are looking for and provided the updated information. Awaiting action by IDIM Consulting on next steps.

**Comment by nvunnamm** [comment]
This is done in following ticket:
Request Non-Production Keycloak Realms for RoadSafety BC Secure File Transfer Proof of Concept (RSFT-POC) Project #957
